### ISSUE TITLE
Build failed for python-publish.yml workflow with error on backend process get_requires_for_build_sdist

### ISSUE THREAD

**Issue by davidusb-geek** [actions/starter-workflows#1790]
Hi, I'm trying to use the python-publish.yml workflow from this repository.
The build step is failing with the following error:

```
Run python -m build
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.[8](https://github.com/davidusb-geek/emhass/actions/runs/3306621368/jobs/5457650511#step:6:9)/x64/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 27[9](https://github.com/davidusb-geek/emhass/actions/runs/3306621368/jobs/5457650511#step:6:10), in get_requires_for_build_sdist
    backend = _build_backend()
  File "/opt/hostedtoolcache/Python/3.[10](https://github.com/davidusb-geek/emhass/actions/runs/3306621368/jobs/5457650511#step:6:11).8/x64/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/importlib/__init__.py", line [12](https://github.com/davidusb-geek/emhass/actions/runs/3306621368/jobs/5457650511#step:6:13)6, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/build-env-yqx36was/lib/python3.10/site-packages/setuptools/__init__.py", line [20](https://github.com/davidusb-geek/emhass/actions/runs/3306621368/jobs/5457650511#step:6:21), in <module>
    from setuptools.dist import Distribution, Feature
  File "/tmp/build-env-yqx36was/lib/python3.10/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools.depends import Require
  File "/tmp/build-env-yqx36was/lib/python3.10/site-packages/setuptools/depends.py", line 7, in <module>
    from .py[33](https://github.com/davidusb-geek/emhass/actions/runs/3306621368/jobs/5457650511#step:6:34)compat import Bytecode
  File "/tmp/build-env-yqx[36](https://github.com/davidusb-geek/emhass/actions/runs/3306621368/jobs/5457650511#step:6:37)was/lib/python3.10/site-packages/setuptools/py33compat.py", line 55, in <module>
    unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
AttributeError: 'HTMLParser' object has no attribute 'unescape'
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools==[40](https://github.com/davidusb-geek/emhass/actions/runs/3306621368/jobs/5457650511#step:6:41).8.0, wheel)
* Getting dependencies for sdist...

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
Error: Process completed with exit code 1.
```

Any hints on a possible solution for this? I'm just trying to automatically upload a Python module to PyPI. This module compiles and uploads perfectly fine manually on Ubuntu 20.04 and Python 3.9.

Here is my complete failed run log:
https://github.com/davidusb-geek/emhass/actions/runs/3306621368/jobs/5457650511

**Comment by davidusb-geek** [comment]
I solved this using this workflow:

```
name: Upload Python Package to PyPI

on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: build
        run: |
          pip install virtualenv
          virtualenv -p /usr/bin/python .venv
          source .venv/bin/activate
          pip install -U twine build packaging
          python -m build
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
```
